/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        /**
          * Just test
         */
        "testFunc": () => Promise<string>;
    }
    interface UiList {
        /**
          * Array of items
         */
        "sourceName": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLUiListElement extends Components.UiList, HTMLStencilElement {
    }
    var HTMLUiListElement: {
        prototype: HTMLUiListElement;
        new (): HTMLUiListElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "ui-list": HTMLUiListElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface UiList {
        "onShowDetails"?: (event: CustomEvent<any>) => void;
        /**
          * Array of items
         */
        "sourceName"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "ui-list": UiList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "ui-list": LocalJSX.UiList & JSXBase.HTMLAttributes<HTMLUiListElement>;
        }
    }
}
